name = "tcex-portal"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "tcex-db"
database_id = "8384dcf4-24d2-4baf-a33c-a617beed6b64"

[[kv_namespaces]]
binding = "SESSIONS"
id = "2ff4e3eb499549fea9291ec36f320cc3"

[[services]]
binding = "ENGINE"
service = "tcex-engine"

[[r2_buckets]]
binding = "DOCUMENTS"
bucket_name = "tcex-documents"
